### ISSUE TITLE
E22 Modlist needs names converted

### ISSUE THREAD

**Issue by Castone22** [Erisia/builder#128]
The current e22 modlist manifest used by ATLauncher isn't... directly... compatible with curse, it's close and we can pull a lot of information out of it, but there are key ones missing to build a functional cursetool manifest.

[instance.json](https://drive.google.com/open?id=12nss-TO6Q4Q4GNbMFZ37YKQ6_Mlfn61P)

We need the associated project name for each mod to assign it to the manifest

For example:
```
Buildcraft Extra Pipes
https://minecraft.curseforge.com/projects/bc-extra-pipes
                                          ^
```                                     
The project name would be bc-extra-pipes
A list of project names and nothing else in a file would do exactly what is needed.

**Comment by Maxwell-lt** [comment]
Made some progress on this, I have about 100 valid project names, and about 130 names that need to be tweaked.

[badnames.txt](https://github.com/Erisia/builder/files/2637871/badnames.txt)
[goodnames.txt](https://github.com/Erisia/builder/files/2637872/goodnames.txt)

**Comment by Castone22** [comment]
this work is done, closing.
