### ISSUE TITLE
E22 Config tweaking

### ISSUE THREAD

**Issue by the-vindex** [Erisia/builder#131]
I'm creating a separate issue for mod configs tweaks.

- [X] Not Enough Wands - decide which should be in and change to RF consumption @lashtear 
- [x] ELN config tweaks @KimBruning

**Comment by Castone22** [comment]
Also adding
- [] RTG configuration (climate and such) @Castone22 
- [] RFTools configuration (Not assigned.)
  - Recipe balancing, turning off resource cards etc
  - This one might be largely ignore-able given our player base is pretty good about not using things that we discourage.

**Comment by Castone22** [comment]
Missed this on the last issue
- [ ] Add Standard client package @the-vindex

**Comment by the-vindex** [comment]
- [ ] Add TickProfiler @the-vindex

**Comment by KimBruning** [comment]
Baughn already got to the ELN config files before me, and wants to make further changes themselves

**Comment by the-vindex** [comment]
- [ ] Fix potion conflicts logged by Forge

**Comment by Maxwell-lt** [comment]
I fixed the potion conflicts in #139.

**Comment by the-vindex** [comment]
Added "standard" mods and TickProfiler in #140. 
Our "standard" additions I've put into tools-1.7.10, so that it's clear what is standard :)
