### ISSUE TITLE
Create server world

### ISSUE THREAD

**Issue by the-vindex** [Erisia/builder#164]
Server world creation keeps hanging at 18 % and lost cities is to blame (removing the mod creates the world ok). Lost cities are needed for progression.

**Comment by Castone22** [comment]
I'm assuming that the config that it's trying to use is the preform after experimenting a bit.  Vanilla lost cities works fine, the sparse cities config from the pack causes the hang

**Comment by Roonas** [comment]
Is it possible we could find the custom config and write a new, similar using the editor in the creation screen, and test that for functionality?

**Comment by the-vindex** [comment]
I've used different seed and world generated ok. Dunno why it was stuck last time. Let's say it's done. Created task to run pregen.
