### ISSUE TITLE
Peaceful switch on server shutdown has broken dragon respawn from CC

### ISSUE THREAD

**Issue by Castone22** [Erisia/builder#26]
A flag reika added in CC is supposed to cause the dragon to respawn

https://github.com/ReikaKalseki/ChromatiCraft/blob/c76e2ab598004dd3426a330c9022877baf2a10a9/ChromaticEventManager.java#L893

It would seem that the peaceful shutdown causes this to break.

**Comment by Castone22** [comment]
In order to progress in CC players need to kill the dragon.  It's required to craft world rifts and a select few other items from CC.

We can probably spawn the dragon manually as players need it as a fix.

**Comment by Baughn** [comment]
The server switches to peaceful *and back*. From looking at that code, it'd spawn the dragon when the End is loaded, and the server will be in hard mode at that time.

**Comment by Castone22** [comment]
Then it might be bugged in another way... hmm.. i'll have to look into this further.

**Comment by Castone22** [comment]
Found out there's a config option we had turned off.  Closing.
