### ISSUE TITLE
Immersive Petroleum oil Deposits

### ISSUE THREAD

**Issue by TheCowKing-moo** [Erisia/builder#58]
Right now we are set to only have 5000 buckets of oil as a max oil deposit for IP. Thats only a few irl days of power before needing to move your mutliblock structure which is kinda driving me away from using the mod altogether. Perhaps we could change the max from 5,000 to 50,000 which should last about 20 irl days and leave the min value at 1,000 buckets so you still need to hunt for a decent sized deposit.

**Comment by Baughn** [comment]
Revelation has this at 5000 to 15000. Good enough>
